# Generated by Django 5.2.4 on 2025-07-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/', verbose_name='Arquivo'),
        ),
    ]
